# Generated by Django 5.0.2 on 2024-03-02 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_attendance', models.CharField(blank=True, max_length=10)),
                ('clock_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.clockrecord')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancesettings')),
            ],
        ),
    ]
