# Generated by Django 5.0.2 on 2024-03-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.client')),
            ],
        ),
    ]
