# Generated by Django 5.0.2 on 2024-03-05 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_assignengineer'),
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.employee'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='AssignEngineer',
        ),
    ]
